### ISSUE TITLE
is there a list of all models used?

### ISSUE THREAD

**Issue by Coderx7** [paulgavrikov/CNN-Filter-DB#2]
Hi, 
Congrats on your paper and thank you for kindly sharing your research results with all of us. 
May I ask if there is a way to know about the list of all models used in this research without resorting to downloading the 47 Gigabytes of data you kindly provided? 
Thanks a lot in advance

**Comment by paulgavrikov** [comment]
Hi,
there's a list of all used models in our supplemental materials, see https://openaccess.thecvf.com/content/CVPR2022/supplemental/Gavrikov_CNN_Filter_DB_CVPR_2022_supplemental.zip (P.19ff)
